theme = "tokyonight"

[editor]
true-color = true
bufferline = "always"
line-number = "relative"
auto-save = false
auto-format = true
auto-pairs = true
scrolloff = 5
mouse = true
middle-click-paste = true
shell = ["zsh", "-c"]

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["diagnostics", "workspace-diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "│"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"
newline = "⏎"

[keys.normal]
C-s = ":w"
C-q = ":q"
